// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: 'postgresql://neondb_owner:npg_brWn9ifgC4Yk@ep-divine-firefly-ahldgyrw-pooler.c-3.us-east-1.aws.neon.tech/kosh_new?sslmode=require&channel_binding=require'
  },
});
